services:
  uwu-admin:
    build:
      context: .
      dockerfile: containers/docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - uwu-data:/data
    restart: unless-stopped

volumes:
  uwu-data:
